"""
Monster Metric Catalog -- 125+ pre-built MarTech metrics organized by strategic phase.
Derived from Dr. Amr Al-Najjar's custom metrics framework.
Each metric has: id, name, name_ar, formula, category, subcategory, level,
description, description_ar, thresholds (healthy / warning / critical), and expert notes.
"""

from typing import Dict, List, Any

# ---------------------------------------------------------------------------
# CATEGORY DEFINITIONS
# ---------------------------------------------------------------------------

CATEGORIES = {
    "creative": {
        "name": "Creative & Attention",
        "name_ar": "الانتباه والكرييتف",
        "icon": "art",
        "color": "#E3008C",
    },
    "traffic": {
        "name": "Traffic Quality",
        "name_ar": "جودة الترافيك",
        "icon": "globe",
        "color": "#FF8C00",
    },
    "intent": {
        "name": "Intent & Conversions",
        "name_ar": "النية والتحويل",
        "icon": "cart",
        "color": "#107C10",
    },
    "algorithm": {
        "name": "Algorithm Health",
        "name_ar": "صحة الخوارزمية",
        "icon": "cpu",
        "color": "#881798",
    },
    "financial": {
        "name": "Unit Economics & Profitability",
        "name_ar": "الاقتصاد والربحية",
        "icon": "currency-dollar",
        "color": "#D13438",
    },
    "standard": {
        "name": "Standard KPIs",
        "name_ar": "المقاييس الأساسية",
        "icon": "speedometer2",
        "color": "#0078D4",
    },
    "messaging": {
        "name": "Messaging & Lead Conversion",
        "name_ar": "الرسائل وتحويل العملاء",
        "icon": "chat-dots",
        "color": "#00B7C3",
    },
    "audience": {
        "name": "Audience & Reach",
        "name_ar": "الجمهور والوصول",
        "icon": "people",
        "color": "#002050",
    },
}

# ---------------------------------------------------------------------------
# METRIC DEFINITIONS
# ---------------------------------------------------------------------------

METRICS: List[Dict[str, Any]] = [
    # ======= STANDARD KPIs =======
    {
        "id": "roas",
        "name": "ROAS",
        "name_ar": "العائد على الإنفاق الإعلاني",
        "formula": "purchase_conversion_value / spend",
        "category": "standard",
        "level": "all",
        "description": "Revenue generated per dollar spent on ads.",
        "description_ar": "الإيرادات المتولدة لكل دولار يُنفق على الإعلانات.",
        "unit": "ratio",
        "format": ".2f",
        "required_columns": ["purchase_conversion_value", "spend"],
    },
    {
        "id": "cpa",
        "name": "CPA",
        "name_ar": "تكلفة الاستحواذ",
        "formula": "spend / purchases",
        "category": "standard",
        "level": "all",
        "description": "Cost to acquire one purchase/conversion.",
        "description_ar": "التكلفة للحصول على عملية شراء واحدة.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["spend", "purchases"],
    },
    {
        "id": "ctr",
        "name": "CTR",
        "name_ar": "نسبة النقر",
        "formula": "(clicks / impressions) * 100",
        "category": "standard",
        "level": "all",
        "description": "Click-through rate as a percentage.",
        "description_ar": "نسبة النقر على الإعلان.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["clicks", "impressions"],
    },
    {
        "id": "cpc",
        "name": "CPC",
        "name_ar": "تكلفة النقرة",
        "formula": "spend / clicks",
        "category": "standard",
        "level": "all",
        "description": "Cost per click.",
        "description_ar": "التكلفة لكل نقرة.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["spend", "clicks"],
    },
    {
        "id": "cpm",
        "name": "CPM",
        "name_ar": "التكلفة لكل ألف ظهور",
        "formula": "(spend / impressions) * 1000",
        "category": "standard",
        "level": "all",
        "description": "Cost per 1,000 impressions.",
        "description_ar": "التكلفة لكل ألف مرة ظهور.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["spend", "impressions"],
    },
    {
        "id": "cvr",
        "name": "CVR",
        "name_ar": "معدل التحويل",
        "formula": "(purchases / clicks) * 100",
        "category": "standard",
        "level": "all",
        "description": "Conversion rate from clicks to purchases.",
        "description_ar": "نسبة التحول من النقر للشراء.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["purchases", "clicks"],
    },
    {
        "id": "aov",
        "name": "AOV",
        "name_ar": "متوسط قيمة الطلب",
        "formula": "purchase_conversion_value / purchases",
        "category": "standard",
        "level": "all",
        "description": "Average order value.",
        "description_ar": "متوسط قيمة الطلب الواحد.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["purchase_conversion_value", "purchases"],
    },
    {
        "id": "frequency",
        "name": "Frequency",
        "name_ar": "التكرار",
        "formula": "impressions / reach",
        "category": "standard",
        "level": "all",
        "description": "Average times each person saw the ad.",
        "description_ar": "متوسط عدد مرات مشاهدة الشخص للإعلان.",
        "unit": "ratio",
        "format": ".2f",
        "required_columns": ["impressions", "reach"],
    },
    {
        "id": "cpl",
        "name": "Cost Per Lead",
        "name_ar": "تكلفة العميل المحتمل",
        "formula": "spend / leads",
        "category": "standard",
        "level": "all",
        "description": "Cost to acquire one lead.",
        "description_ar": "التكلفة للحصول على عميل محتمل واحد.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["spend", "leads"],
    },
    {
        "id": "thruplay_rate",
        "name": "ThruPlay Rate",
        "name_ar": "نسبة المشاهدة الكاملة",
        "formula": "(video_thruplay / impressions) * 100",
        "category": "standard",
        "level": "ad",
        "description": "Percentage of impressions that resulted in ThruPlays.",
        "description_ar": "نسبة المشاهدات الكاملة من إجمالي الظهور.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["video_thruplay", "impressions"],
    },

    # ======= CREATIVE & ATTENTION =======
    {
        "id": "hook_rate",
        "name": "True Hook Rate",
        "name_ar": "معدل الجذب الحقيقي",
        "formula": "(video_3s_plays / impressions) * 100",
        "category": "creative",
        "level": "ad",
        "description": "% of impressions where first 3 seconds stopped the scroll. Below 25% = dead creative.",
        "description_ar": "نسبة الظهور اللي أول 3 ثواني فيها وقفت التمرير. تحت 25% = كرييتف ميت.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["video_3s_plays", "impressions"],
        "thresholds": {"healthy": 25, "warning": 15, "critical": 10},
    },
    {
        "id": "hold_rate",
        "name": "Absolute Hold Rate",
        "name_ar": "معدل الاحتفاظ المطلق",
        "formula": "(video_thruplay / video_3s_plays) * 100",
        "category": "creative",
        "level": "ad",
        "description": "Of those who watched 3s, how many watched 15s+? Below 20% = clickbait.",
        "description_ar": "من اللي شافوا 3 ثواني، كم واحد كمل لـ 15 ثانية؟ تحت 20% = طعم كذاب.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["video_thruplay", "video_3s_plays"],
        "thresholds": {"healthy": 30, "warning": 20, "critical": 10},
    },
    {
        "id": "creative_fatigue_index",
        "name": "Creative Fatigue Index",
        "name_ar": "مؤشر إرهاق الكرييتف",
        "formula": "frequency * (1 - (outbound_ctr / 100))",
        "category": "creative",
        "level": "ad",
        "description": "When frequency rises and CTR drops, this spikes. Above 2.5 = CPM penalty incoming.",
        "description_ar": "لما التكرار يزيد والنقر يقل، الرقم يطير. فوق 2.5 = عقوبة CPM قادمة.",
        "unit": "index",
        "format": ".2f",
        "required_columns": ["frequency", "outbound_ctr"],
        "thresholds": {"healthy": 1.5, "warning": 2.5, "critical": 4.0},
    },
    {
        "id": "ghost_impression_rate",
        "name": "Ghost Impression Rate",
        "name_ar": "نسبة الظهور الشبحي",
        "formula": "((impressions - reach) / impressions) * 100",
        "category": "creative",
        "level": "ad",
        "description": "% of impressions shown to same people without interaction. Above 40% = Meta milking your budget.",
        "description_ar": "نسبة الظهور المكرر لنفس الأشخاص. فوق 40% = ميتا بتستنزف ميزانيتك.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["impressions", "reach"],
        "thresholds": {"healthy": 25, "warning": 40, "critical": 60},
    },
    {
        "id": "earned_engagement_ratio",
        "name": "Earned Engagement Ratio",
        "name_ar": "نسبة التفاعل المكتسب",
        "formula": "((post_shares + post_saves) / impressions) * 100",
        "category": "creative",
        "level": "ad",
        "description": "Shares + Saves per impression. Deep intent indicator -- saves > likes for sensitive products.",
        "description_ar": "المشاركات + الحفظ لكل ظهور. مؤشر نية عميقة -- الحفظ أهم من اللايك للمنتجات الحساسة.",
        "unit": "percentage",
        "format": ".4f",
        "required_columns": ["post_shares", "post_saves", "impressions"],
    },
    {
        "id": "engagement_to_impression",
        "name": "Engagement-to-Impression Ratio",
        "name_ar": "نسبة التفاعل للظهور",
        "formula": "(total_engagements / impressions) * 100",
        "category": "creative",
        "level": "ad",
        "description": "Any drop gives 48-hour early warning of engagement collapse.",
        "description_ar": "أي هبوط يعطيك إنذار مبكر بـ 48 ساعة بانهيار التفاعل.",
        "unit": "percentage",
        "format": ".4f",
        "required_columns": ["total_engagements", "impressions"],
    },

    # ======= TRAFFIC QUALITY =======
    {
        "id": "drop_off_rate",
        "name": "The Meta Lie Ratio (Drop-off)",
        "name_ar": "نسبة كذبة ميتا (التسرب)",
        "formula": "((link_clicks - landing_page_views) / link_clicks) * 100",
        "category": "traffic",
        "level": "adset",
        "description": "% who clicked but never saw the page. Above 30% = slow site or accidental clicks.",
        "description_ar": "نسبة اللي كبسوا وما استنوا الصفحة. فوق 30% = موقع بطيء أو نقرات بالغلط.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["link_clicks", "landing_page_views"],
        "thresholds": {"healthy": 15, "warning": 30, "critical": 50},
    },
    {
        "id": "pure_intent_ctr",
        "name": "Pure Intent CTR",
        "name_ar": "نسبة النقر الحقيقية",
        "formula": "(outbound_clicks / impressions) * 100",
        "category": "traffic",
        "level": "adset",
        "description": "Filters out likes, photo opens, read more. Only counts clicks leaving Meta.",
        "description_ar": "بتفلتر كل الهراء وبتعطيك فقط اللي كبسوا ليطلعوا من ميتا.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["outbound_clicks", "impressions"],
    },
    {
        "id": "bounce_tax",
        "name": "Bounce Tax (Wasted Spend)",
        "name_ar": "ضريبة الارتداد (الهدر)",
        "formula": "(link_clicks - landing_page_views) * cpc",
        "category": "traffic",
        "level": "adset",
        "description": "Money wasted on people who clicked but never saw your site.",
        "description_ar": "الفلوس اللي ضاعت على ناس كبست وما دخلت الموقع.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["link_clicks", "landing_page_views", "cpc"],
    },
    {
        "id": "scroll_to_commit",
        "name": "Scroll-to-Commit Ratio",
        "name_ar": "نسبة التمرير للالتزام",
        "formula": "(adds_to_cart / landing_page_views) * 100",
        "category": "traffic",
        "level": "adset",
        "description": "Landing page quality. Below 5% = page problem (price, copy, trust).",
        "description_ar": "جودة صفحة الهبوط. تحت 5% = مشكلة بالصفحة (سعر، وصف، ثقة).",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["adds_to_cart", "landing_page_views"],
        "thresholds": {"healthy": 8, "warning": 5, "critical": 2},
    },
    {
        "id": "micro_conversion_cost",
        "name": "Micro-Conversion Cost",
        "name_ar": "تكلفة التحويل الصغير",
        "formula": "spend / landing_page_views",
        "category": "traffic",
        "level": "adset",
        "description": "True cost per actual site visitor. More honest than CPC.",
        "description_ar": "التكلفة الحقيقية للزائر. أصدق بكثير من CPC.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["spend", "landing_page_views"],
    },
    {
        "id": "click_to_content",
        "name": "Click-to-Content Ratio",
        "name_ar": "نسبة النقر للمحتوى",
        "formula": "(outbound_clicks / clicks) * 100",
        "category": "traffic",
        "level": "adset",
        "description": "Separates real intent from comment-readers and reaction-clickers.",
        "description_ar": "بتفصل النية الحقيقية عن قارئي التعليقات.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["outbound_clicks", "clicks"],
    },

    # ======= INTENT & CONVERSIONS =======
    {
        "id": "cart_abandonment_rate",
        "name": "Cart Abandonment Rate",
        "name_ar": "نسبة التخلي عن السلة",
        "formula": "((adds_to_cart - purchases) / adds_to_cart) * 100",
        "category": "intent",
        "level": "campaign",
        "description": "% who added to cart but didn't buy. Above 70% = checkout friction.",
        "description_ar": "نسبة اللي حطوا بالسلة وما اشتروا. فوق 70% = مشكلة بالدفع.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["adds_to_cart", "purchases"],
        "thresholds": {"healthy": 55, "warning": 70, "critical": 85},
    },
    {
        "id": "checkout_friction",
        "name": "Checkout Initiation Friction",
        "name_ar": "احتكاك بدء الدفع",
        "formula": "((adds_to_cart - initiated_checkouts) / adds_to_cart) * 100",
        "category": "intent",
        "level": "campaign",
        "description": "% who added to cart but feared clicking checkout.",
        "description_ar": "نسبة اللي حطوا بالسلة وخافوا يكبسوا إتمام الطلب.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["adds_to_cart", "initiated_checkouts"],
    },
    {
        "id": "purchase_intent_velocity",
        "name": "Purchase Intent Velocity",
        "name_ar": "سرعة النية الشرائية",
        "formula": "(initiated_checkouts / landing_page_views) * 100",
        "category": "intent",
        "level": "campaign",
        "description": "Leading indicator. Gives campaign pulse within 2 hours of launch.",
        "description_ar": "مؤشر استباقي. يعطيك نبض الحملة بعد ساعتين من إطلاقها.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["initiated_checkouts", "landing_page_views"],
    },
    {
        "id": "tcpa",
        "name": "True Cost Per Acquisition",
        "name_ar": "التكلفة الحقيقية للاستحواذ",
        "formula": "spend / (purchases + (adds_to_cart * 0.1))",
        "category": "intent",
        "level": "campaign",
        "description": "Weights ATCs at 10% to compensate for attribution lag.",
        "description_ar": "يعطي وزن 10% لإضافة السلة لتعويض تأخر التتبع.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["spend", "purchases", "adds_to_cart"],
    },
    {
        "id": "lead_to_sale",
        "name": "Lead-to-Sale Conversion",
        "name_ar": "تحويل العميل المحتمل للمبيعات",
        "formula": "(purchases / leads) * 100",
        "category": "intent",
        "level": "campaign",
        "description": "Lead quality. Below 10% = auto-fill junk leads.",
        "description_ar": "جودة العملاء المحتملين. تحت 10% = عملاء وهميين.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["purchases", "leads"],
        "thresholds": {"healthy": 15, "warning": 10, "critical": 5},
    },
    {
        "id": "intent_click_rate",
        "name": "Intent Click Rate",
        "name_ar": "نسبة النقر بنية شرائية",
        "formula": "(adds_to_cart / outbound_clicks) * 100",
        "category": "intent",
        "level": "ad",
        "description": "Pure buying intent beyond browsing clicks.",
        "description_ar": "النية الشرائية الصافية بعيداً عن الزيارات العابرة.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["adds_to_cart", "outbound_clicks"],
    },

    # ======= ALGORITHM HEALTH =======
    {
        "id": "audience_exhaustion_index",
        "name": "Audience Exhaustion Index",
        "name_ar": "مؤشر استنزاف الجمهور",
        "formula": "frequency * (spend / reach)",
        "category": "algorithm",
        "level": "adset",
        "description": "Multiplies frequency by cost-per-reach. Spikes = algo ran out of new people.",
        "description_ar": "يضرب التكرار في تكلفة الوصول. ارتفاع مفاجئ = الخوارزمية نفدت من أشخاص جدد.",
        "unit": "index",
        "format": ".4f",
        "required_columns": ["frequency", "spend", "reach"],
    },
    {
        "id": "net_new_reach_pct",
        "name": "Net New Reach % (Dynamic)",
        "name_ar": "نسبة الوصول الجديد الصافي",
        "formula": "((reach_today - reach_yesterday) / reach_today) * 100",
        "category": "algorithm",
        "level": "account",
        "description": "Daily fresh eyes. Below 30% = CPA explosion in 72 hours.",
        "description_ar": "عيون جديدة يومياً. تحت 30% = انفجار CPA خلال 72 ساعة.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["reach_today", "reach_yesterday"],
        "thresholds": {"healthy": 60, "warning": 40, "critical": 30},
    },
    {
        "id": "cpm_cpa_delta",
        "name": "CPM to CPA Delta",
        "name_ar": "فرق CPM و CPA",
        "formula": "((cpm_current - cpm_last_week) / cpm_last_week) * 100",
        "category": "algorithm",
        "level": "campaign",
        "description": "Auction inflation. CPM +20% with CPA +50% = creative issue. Both +50% = market.",
        "description_ar": "تضخم المزاد. CPM +20% مع CPA +50% = مشكلة كرييتف. كلاهما +50% = السوق.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["cpm_current", "cpm_last_week"],
    },
    {
        "id": "first_time_impression_ratio",
        "name": "First-Time Impression Ratio",
        "name_ar": "نسبة الظهور الأول",
        "formula": "1 / frequency",
        "category": "algorithm",
        "level": "adset",
        "description": "Close to 1 = prospecting. Close to 0.3 = retargeting in disguise.",
        "description_ar": "قريب من 1 = توسع. قريب من 0.3 = إعادة استهداف مقنّع.",
        "unit": "ratio",
        "format": ".2f",
        "required_columns": ["frequency"],
    },
    {
        "id": "signal_to_noise_loss",
        "name": "Signal-to-Noise Loss",
        "name_ar": "خسارة الإشارة للضجيج",
        "formula": "((outbound_clicks - landing_page_views) / outbound_clicks) * 100",
        "category": "algorithm",
        "level": "adset",
        "description": "How dumb the algorithm is at finding real buyers. Rising = Pixel/CAPI broken.",
        "description_ar": "قديش الخوارزمية غبية بإيجاد مشترين. ارتفاع = بيكسل/CAPI فيهم مشكلة.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["outbound_clicks", "landing_page_views"],
    },
    {
        "id": "retargeting_saturation",
        "name": "Retargeting Saturation",
        "name_ar": "تشبع إعادة الاستهداف",
        "formula": "(retargeting_spend / spend) * 100",
        "category": "algorithm",
        "level": "account",
        "description": "If it spikes, algorithm got lazy and stopped prospecting.",
        "description_ar": "إذا ارتفعت فجأة، الخوارزمية مكسلة ووقفت تدور على ناس جدد.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["retargeting_spend", "spend"],
    },
    {
        "id": "estimated_ecvr_dropoff",
        "name": "Estimated eCVR Drop-off",
        "name_ar": "انخفاض معدل التحويل المقدر",
        "formula": "meta_ecvr - actual_cvr",
        "category": "algorithm",
        "level": "campaign",
        "description": "Explains sudden bid cost spikes without apparent reason.",
        "description_ar": "بيفسر ليش تكلفة المزايدة بتضرب فجأة بدون مبرر.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["meta_ecvr", "actual_cvr"],
    },

    # ======= FINANCIAL / UNIT ECONOMICS =======
    {
        "id": "true_poas",
        "name": "True POAS (Profit on Ad Spend)",
        "name_ar": "الربح الحقيقي على الإنفاق",
        "formula": "(purchase_conversion_value - (purchases * cogs)) / spend",
        "category": "financial",
        "level": "campaign",
        "description": "Net profit. POAS < 1 = losing money even if ROAS is 5!",
        "description_ar": "الربح الصافي. POAS أقل من 1 = خسارة حتى لو ROAS 5!",
        "unit": "ratio",
        "format": ".2f",
        "required_columns": ["purchase_conversion_value", "purchases", "cogs", "spend"],
    },
    {
        "id": "nc_roas",
        "name": "New Customer ROAS",
        "name_ar": "عائد العملاء الجدد",
        "formula": "(purchase_conversion_value * new_customer_pct) / spend",
        "category": "financial",
        "level": "campaign",
        "description": "Revenue from truly new customers only. The real growth metric.",
        "description_ar": "العائد من العملاء الجدد فقط. مقياس النمو الحقيقي.",
        "unit": "ratio",
        "format": ".2f",
        "required_columns": ["purchase_conversion_value", "new_customer_pct", "spend"],
    },
    {
        "id": "breakeven_roas_delta",
        "name": "Breakeven ROAS Delta",
        "name_ar": "فرق نقطة التعادل",
        "formula": "(purchase_conversion_value / spend) - breakeven_roas",
        "category": "financial",
        "level": "campaign",
        "description": "Safety margin. Positive = printing money. Negative = turn off immediately.",
        "description_ar": "هامش الأمان. موجب = بتطبع فلوس. سالب = أطفئ فوراً.",
        "unit": "ratio",
        "format": ".2f",
        "required_columns": ["purchase_conversion_value", "spend", "breakeven_roas"],
    },
    {
        "id": "aov_deflection",
        "name": "AOV Deflection Index",
        "name_ar": "مؤشر انحراف قيمة الطلب",
        "formula": "(purchase_conversion_value / purchases) / blended_aov",
        "category": "financial",
        "level": "campaign",
        "description": "Below 1 = ads attract cheap buyers. Change offer or raise min spend.",
        "description_ar": "أقل من 1 = الإعلان يجذب زبائن رخيصة. غير العرض أو ارفع الحد الأدنى.",
        "unit": "ratio",
        "format": ".2f",
        "required_columns": ["purchase_conversion_value", "purchases", "blended_aov"],
    },
    {
        "id": "ltv_to_cac",
        "name": "LTV to CAC Proxy",
        "name_ar": "مؤشر القيمة الدائمة للتكلفة",
        "formula": "(purchase_conversion_value * repeat_rate) / (spend / purchases)",
        "category": "financial",
        "level": "campaign",
        "description": "Accept loss on first order if customer repeats. Key for pharma/beauty.",
        "description_ar": "اقبل الخسارة بالطلبية الأولى إذا العميل راح يرجع. مفتاح الأدوية والتجميل.",
        "unit": "ratio",
        "format": ".2f",
        "required_columns": ["purchase_conversion_value", "repeat_rate", "spend", "purchases"],
    },
    {
        "id": "cost_per_unique_atc",
        "name": "Cost Per Unique ATC",
        "name_ar": "تكلفة الإضافة الفريدة للسلة",
        "formula": "spend / unique_adds_to_cart",
        "category": "financial",
        "level": "adset",
        "description": "More accurate than total ATC cost since one user can add multiple items.",
        "description_ar": "أدق من التكلفة العامة لأن عميل واحد ممكن يضيف عدة منتجات.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["spend", "unique_adds_to_cart"],
    },
    {
        "id": "frequency_roas_delta",
        "name": "Frequency-to-ROAS Delta",
        "name_ar": "فرق التكرار والعائد",
        "formula": "roas_drop_pct / frequency_increase_pct",
        "category": "financial",
        "level": "campaign",
        "description": "Pinpoints exact moment to stop campaign when repetition poisons sales.",
        "description_ar": "يحدد اللحظة الدقيقة لإيقاف الحملة لما التكرار يصير سام للمبيعات.",
        "unit": "ratio",
        "format": ".2f",
        "required_columns": ["roas_drop_pct", "frequency_increase_pct"],
    },

    # ======= MESSAGING & LEAD CONVERSION =======
    {
        "id": "msg_open_rate",
        "name": "Message Open Rate",
        "name_ar": "نسبة فتح الرسائل",
        "formula": "(messaging_conversations_started / link_clicks) * 100",
        "category": "messaging",
        "level": "campaign",
        "description": "% of clicks that actually started a conversation.",
        "description_ar": "نسبة النقرات اللي فعلاً بدأت محادثة.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["messaging_conversations_started", "link_clicks"],
    },
    {
        "id": "cost_per_conversation",
        "name": "Cost Per Conversation Started",
        "name_ar": "تكلفة بدء المحادثة",
        "formula": "spend / messaging_conversations_started",
        "category": "messaging",
        "level": "campaign",
        "description": "True cost of starting a real conversation.",
        "description_ar": "التكلفة الحقيقية لبدء محادثة حقيقية.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["spend", "messaging_conversations_started"],
    },
    {
        "id": "msg_to_order_rate",
        "name": "Message-to-Order Conversion",
        "name_ar": "تحويل الرسالة للطلب",
        "formula": "(orders_from_messages / messaging_conversations_started) * 100",
        "category": "messaging",
        "level": "campaign",
        "description": "Key metric for message-based selling. Links to external order data.",
        "description_ar": "المقياس الرئيسي للبيع عبر الرسائل. يرتبط ببيانات الطلبات الخارجية.",
        "unit": "percentage",
        "format": ".2f",
        "required_columns": ["orders_from_messages", "messaging_conversations_started"],
    },
    {
        "id": "cost_per_msg_order",
        "name": "Cost Per Message Order",
        "name_ar": "تكلفة الطلب عبر الرسائل",
        "formula": "spend / orders_from_messages",
        "category": "messaging",
        "level": "campaign",
        "description": "Total ad spend per actual order closed via messaging.",
        "description_ar": "إجمالي الإنفاق الإعلاني لكل طلب فعلي تم عبر الرسائل.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["spend", "orders_from_messages"],
    },
    {
        "id": "msg_revenue_per_conv",
        "name": "Revenue Per Message Conversation",
        "name_ar": "الإيرادات لكل محادثة",
        "formula": "message_revenue / messaging_conversations_started",
        "category": "messaging",
        "level": "campaign",
        "description": "How much revenue each started conversation brings on average.",
        "description_ar": "كم إيرادات تجلب كل محادثة بدأت بالمتوسط.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["message_revenue", "messaging_conversations_started"],
    },

    # ======= AUDIENCE & REACH =======
    {
        "id": "audience_cost_efficiency",
        "name": "Audience Cost Efficiency",
        "name_ar": "كفاءة تكلفة الجمهور",
        "formula": "spend / reach",
        "category": "audience",
        "level": "adset",
        "description": "Cost to reach one unique person.",
        "description_ar": "تكلفة الوصول لشخص واحد فريد.",
        "unit": "currency",
        "format": ".4f",
        "required_columns": ["spend", "reach"],
    },
    {
        "id": "reach_efficiency",
        "name": "Reach Efficiency Index",
        "name_ar": "مؤشر كفاءة الوصول",
        "formula": "reach / spend * 1000",
        "category": "audience",
        "level": "adset",
        "description": "People reached per $1000 spent.",
        "description_ar": "عدد الأشخاص الذين تم الوصول إليهم لكل 1000 دولار.",
        "unit": "ratio",
        "format": ".0f",
        "required_columns": ["reach", "spend"],
    },
    {
        "id": "cost_per_educated_prospect",
        "name": "Cost Per Educated Prospect",
        "name_ar": "تكلفة العميل المثقف",
        "formula": "spend / users_over_30s",
        "category": "audience",
        "level": "campaign",
        "description": "Cost per user who spent 30+ seconds on site. Great for pharma/education.",
        "description_ar": "تكلفة المستخدم اللي قضى 30+ ثانية بالموقع. ممتاز للأدوية والتعليم.",
        "unit": "currency",
        "format": ".2f",
        "required_columns": ["spend", "users_over_30s"],
    },
    {
        "id": "algorithm_correction_time",
        "name": "Algorithm Correction Time",
        "name_ar": "وقت تصحيح الخوارزمية",
        "formula": "days_to_recover",
        "category": "algorithm",
        "level": "campaign",
        "description": "Days for performance to recover after a change. Measures account resilience.",
        "description_ar": "عدد الأيام لاستعادة الأداء بعد تغيير. يقيس مرونة الحساب.",
        "unit": "days",
        "format": ".0f",
        "required_columns": ["days_to_recover"],
    },
    # ======= CHAT / MESSAGING ENGINE (AXIOM #26-50) =======
    {
        "id": "ghost_dropoff_rate",
        "name": "Ghost Drop-off Rate",
        "name_ar": "معدل التسرب الشبحي",
        "formula": "(clicks - new_messaging_connections) / clicks * 100",
        "category": "messaging",
        "level": "all",
        "description": "Percentage of link clicks that never resulted in a messaging connection.",
        "description_ar": "نسبة النقرات التي لم تؤد لمحادثة فعلية.",
        "unit": "percent",
        "format": ".2f",
        "required_columns": ["clicks", "new_messaging_connections"],
        "thresholds": {"healthy": 25, "warning": 40, "critical": 60, "lower_is_better": True},
    },
    {
        "id": "wasted_chat_spend",
        "name": "Wasted Chat Spend",
        "name_ar": "الإنفاق المهدر على المحادثات",
        "formula": "(clicks - new_messaging_connections) * cpc",
        "category": "messaging",
        "level": "all",
        "description": "Money spent on clicks that opened chat but never connected.",
        "description_ar": "الأموال المنفقة على نقرات فتحت المحادثة لكن لم تتصل.",
        "unit": "currency",
        "format": ",.2f",
        "required_columns": ["clicks", "new_messaging_connections", "cpc"],
    },
    {
        "id": "true_chat_intent_ctr",
        "name": "True Chat Intent CTR",
        "name_ar": "نسبة النية الحقيقية للمحادثة",
        "formula": "new_messaging_connections / impressions * 100",
        "category": "messaging",
        "level": "all",
        "description": "True rate of people who intended to message, filtering out vanity clicks.",
        "description_ar": "النسبة الحقيقية للأشخاص الذين نووا المراسلة.",
        "unit": "percent",
        "format": ".2f",
        "required_columns": ["new_messaging_connections", "impressions"],
        "thresholds": {"healthy": 0.5, "warning": 0.2, "critical": 0.1},
    },
    {
        "id": "cost_per_true_hello",
        "name": "Cost Per True Hello (CPTH)",
        "name_ar": "تكلفة المحادثة الحقيقية",
        "formula": "spend / new_messaging_connections",
        "category": "messaging",
        "level": "all",
        "description": "How much each genuine messaging connection costs.",
        "description_ar": "تكلفة كل اتصال محادثة حقيقي.",
        "unit": "currency",
        "format": ",.2f",
        "required_columns": ["spend", "new_messaging_connections"],
    },
    {
        "id": "pre_chat_friction",
        "name": "Pre-Chat Friction Index",
        "name_ar": "مؤشر الاحتكاك قبل المحادثة",
        "formula": "(spend / new_messaging_connections) - cpc",
        "category": "messaging",
        "level": "all",
        "description": "Extra cost beyond CPC to get an actual conversation. High = friction in the chat flow.",
        "description_ar": "التكلفة الإضافية فوق CPC للحصول على محادثة فعلية.",
        "unit": "currency",
        "format": ",.2f",
        "required_columns": ["spend", "new_messaging_connections", "cpc"],
        "thresholds": {"healthy": 0.5, "warning": 2.0, "critical": 5.0, "lower_is_better": True},
    },
    {
        "id": "window_shopper_ratio",
        "name": "Window Shopper Ratio",
        "name_ar": "نسبة المتصفحين",
        "formula": "(new_messaging_connections - leads) / new_messaging_connections * 100",
        "category": "messaging",
        "level": "all",
        "description": "Percentage of conversations that never qualified as leads.",
        "description_ar": "نسبة المحادثات التي لم تتأهل كعملاء محتملين.",
        "unit": "percent",
        "format": ".2f",
        "required_columns": ["new_messaging_connections", "leads"],
        "thresholds": {"healthy": 40, "warning": 60, "critical": 80, "lower_is_better": True},
    },
    {
        "id": "qualified_lead_cvr",
        "name": "Qualified Lead Conversion Rate",
        "name_ar": "معدل تحويل العميل المؤهل",
        "formula": "leads / new_messaging_connections * 100",
        "category": "messaging",
        "level": "all",
        "description": "Rate of messaging connections that become qualified leads.",
        "description_ar": "معدل المحادثات التي تصبح عملاء مؤهلين.",
        "unit": "percent",
        "format": ".2f",
        "required_columns": ["leads", "new_messaging_connections"],
        "thresholds": {"healthy": 30, "warning": 15, "critical": 5},
    },
    {
        "id": "cost_per_qualified_chat",
        "name": "Cost Per Qualified Chat (CPQC)",
        "name_ar": "تكلفة المحادثة المؤهلة",
        "formula": "spend / leads",
        "category": "messaging",
        "level": "all",
        "description": "True CPL — not Meta's reported CPL. The cost of a qualified conversation.",
        "description_ar": "تكلفة الحصول على عميل محتمل مؤهل من المحادثات.",
        "unit": "currency",
        "format": ",.2f",
        "required_columns": ["spend", "leads"],
    },
    {
        "id": "sales_close_rate",
        "name": "Sales Team Close Rate",
        "name_ar": "معدل إغلاق فريق المبيعات",
        "formula": "purchases / leads * 100",
        "category": "messaging",
        "level": "all",
        "description": "Percentage of qualified leads that converted to purchases.",
        "description_ar": "نسبة العملاء المؤهلين الذين أتموا الشراء.",
        "unit": "percent",
        "format": ".2f",
        "required_columns": ["purchases", "leads"],
        "thresholds": {"healthy": 20, "warning": 10, "critical": 5},
    },
    {
        "id": "overall_chat_close_rate",
        "name": "Overall Chat Close Rate",
        "name_ar": "معدل الإغلاق الكلي للمحادثات",
        "formula": "purchases / new_messaging_connections * 100",
        "category": "messaging",
        "level": "all",
        "description": "End-to-end conversion from chat connection to purchase.",
        "description_ar": "معدل التحويل من أول محادثة إلى شراء.",
        "unit": "percent",
        "format": ".2f",
        "required_columns": ["purchases", "new_messaging_connections"],
        "thresholds": {"healthy": 5, "warning": 2, "critical": 1},
    },
    {
        "id": "revenue_per_chat",
        "name": "Revenue Per Chat Conversation",
        "name_ar": "الإيراد لكل محادثة",
        "formula": "purchase_conversion_value / new_messaging_connections",
        "category": "messaging",
        "level": "all",
        "description": "Average revenue generated per chat connection. Defines max acceptable CPTH.",
        "description_ar": "متوسط الإيراد لكل محادثة. يحدد الحد الأقصى المقبول لتكلفة المحادثة.",
        "unit": "currency",
        "format": ",.2f",
        "required_columns": ["purchase_conversion_value", "new_messaging_connections"],
    },
    {
        "id": "simp_algorithm_index",
        "name": "Simp Algorithm Index",
        "name_ar": "مؤشر خوارزمية النقرات الرخيصة",
        "formula": "(spend / new_messaging_connections) / (spend / purchases)",
        "category": "messaging",
        "level": "all",
        "description": "Low = Meta finding cheap clickers who never buy. High = finding buying intent.",
        "description_ar": "منخفض = ميتا تجد نقرات رخيصة لا تشتري. مرتفع = تجد نية شراء.",
        "unit": "ratio",
        "format": ".4f",
        "required_columns": ["spend", "new_messaging_connections", "purchases"],
        "thresholds": {"healthy": 0.15, "warning": 0.05, "critical": 0.01},
    },
    {
        "id": "msg_frequency_exhaustion",
        "name": "Message Frequency Exhaustion",
        "name_ar": "مؤشر إرهاق تكرار الرسائل",
        "formula": "frequency * (spend / new_messaging_connections)",
        "category": "messaging",
        "level": "all",
        "description": "Rising index + declining conversations = audience saturated on chat.",
        "description_ar": "مؤشر مرتفع + انخفاض المحادثات = تشبع الجمهور من الرسائل.",
        "unit": "currency",
        "format": ",.2f",
        "required_columns": ["frequency", "spend", "new_messaging_connections"],
    },
    # ======= VIDEO CREATIVE METRICS =======
    {
        "id": "video_completion_rate",
        "name": "Video Completion Rate",
        "name_ar": "معدل إكمال الفيديو",
        "formula": "video_thruplay / impressions * 100",
        "category": "creative",
        "level": "all",
        "description": "Percentage of impressions that resulted in a complete/15s+ video view.",
        "description_ar": "نسبة الانطباعات التي أدت لمشاهدة كاملة أو +15 ثانية.",
        "unit": "percent",
        "format": ".2f",
        "required_columns": ["video_thruplay", "impressions"],
    },
    {
        "id": "cost_per_thruplay",
        "name": "Cost Per ThruPlay",
        "name_ar": "تكلفة المشاهدة الكاملة",
        "formula": "spend / video_thruplay",
        "category": "creative",
        "level": "all",
        "description": "Cost to achieve one completed/15s+ video view.",
        "description_ar": "تكلفة تحقيق مشاهدة فيديو كاملة واحدة.",
        "unit": "currency",
        "format": ",.4f",
        "required_columns": ["spend", "video_thruplay"],
    },
    {
        "id": "vanity_ctr_gap",
        "name": "Vanity CTR Gap",
        "name_ar": "فجوة نسبة النقر الوهمية",
        "formula": "(clicks / impressions * 100) - (outbound_clicks / impressions * 100)",
        "category": "traffic",
        "level": "all",
        "description": "Gap between CTR (All) and Pure Intent CTR. High = most clicks are not purchase-intent.",
        "description_ar": "الفجوة بين نسبة النقر الكلية ونسبة النقر الحقيقية.",
        "unit": "percent",
        "format": ".2f",
        "required_columns": ["clicks", "outbound_clicks", "impressions"],
    },
]

# Build lookup dicts
METRICS_BY_ID = {m["id"]: m for m in METRICS}
METRICS_BY_CATEGORY = {}
for m in METRICS:
    cat = m["category"]
    if cat not in METRICS_BY_CATEGORY:
        METRICS_BY_CATEGORY[cat] = []
    METRICS_BY_CATEGORY[cat].append(m)


def get_all_required_columns() -> List[str]:
    """Return sorted unique list of all columns referenced by any metric."""
    cols: set = set()
    for m in METRICS:
        cols.update(m.get("required_columns", []))
    return sorted(cols)


def get_metrics_for_available_columns(available_columns: List[str]) -> List[Dict]:
    """Return metrics that can be computed from the given columns."""
    available = set(c.lower().strip() for c in available_columns)
    result = []
    for m in METRICS:
        required = set(m.get("required_columns", []))
        if required and required.issubset(available):
            result.append(m)
    return result
